Repository CGAInstitution/proyectoud4-ti-wuan, pull requests merged in 2025-02, with the labels that each got.

#3 Develop
  src/main/java/madstodolist/service/InitDbService.java
  src/main/resources/application.properties
  src/main/resources/database/ScriptBBDD.sql
Labels: enhancement

#5 Sync login with index
  src/main/java/madstodolist/controller/LoginController.java
Labels: enhancement

#14 feat(TiendaController.java): add TiendaController
  pom.xml
  src/main/java/madstodolist/controller/TiendaController.java
  src/main/resources/templates/formLogin.html
  src/main/resources/templates/index.html
Labels: enhancement

#17 Add exit to log in and update index.html
  src/main/java/madstodolist/controller/LoginController.java
  src/main/java/madstodolist/controller/TiendaController.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/img/camiseta_lol.jpg
  src/main/resources/static/img/figura_lol.jpg
  src/main/resources/static/img/teclado_lol.jpg
  src/main/resources/templates/index.html
Labels: enhancement

#27 Feature
  pom.xml
  src/main/java/madstodolist/TiendaLolApplication.java
  src/main/java/madstodolist/controller/AdminController.java
  src/main/java/madstodolist/controller/PerfilController.java
  src/main/java/madstodolist/dto/RegistroData.java
  src/main/java/madstodolist/dto/UsuarioData.java
  src/main/java/madstodolist/model/Pedido.java
  src/main/java/madstodolist/model/Usuario.java
  src/main/java/madstodolist/repository/DetallePedidoRepository.java
  src/main/java/madstodolist/repository/PedidoRepository.java
  src/main/java/madstodolist/service/UsuarioService.java
  src/main/resources/application.properties
  src/main/resources/templates/admin.html
  src/main/resources/templates/index.html
  src/main/resources/templates/modals.html
  src/main/resources/templates/perfil.html
Labels: enhancement

#28 Feature
  pom.xml
  src/main/java/madstodolist/Application.java
  src/main/java/madstodolist/TiendaLolApplication.java
  src/main/java/madstodolist/controller/AdminController.java
  src/main/java/madstodolist/controller/CamisetasController.java
  src/main/java/madstodolist/controller/CarritoController.java
  src/main/java/madstodolist/controller/FigurasController.java
  src/main/java/madstodolist/controller/LoginController.java
  src/main/java/madstodolist/controller/PerfilController.java
  src/main/java/madstodolist/controller/TecladosController.java
  src/main/java/madstodolist/controller/TiendaController.java
  src/main/java/madstodolist/dto/CategoriaData.java
  src/main/java/madstodolist/dto/PedidoData.java
  src/main/java/madstodolist/dto/ProductoData.java
  src/main/java/madstodolist/dto/RegistroData.java
  src/main/java/madstodolist/dto/UsuarioData.java
  src/main/java/madstodolist/model/DetallePedido.java
  src/main/java/madstodolist/model/Inventario.java
  src/main/java/madstodolist/model/Pedido.java
  src/main/java/madstodolist/model/PedidoProducto.java
  src/main/java/madstodolist/repository/InventarioRepository.java
  src/main/java/madstodolist/repository/PedidoRepository.java
  src/main/java/madstodolist/repository/ProductoRepository.java
  src/main/java/madstodolist/service/CategoriaService.java
  src/main/java/madstodolist/service/PedidoService.java
  src/main/java/madstodolist/service/ProductoService.java
  src/main/java/madstodolist/service/UsuarioService.java
  src/main/resources/application.properties
  src/main/resources/static/img/a
  src/main/resources/templates/camisetas.html
  src/main/resources/templates/cesta.html
  src/main/resources/templates/figuras.html
  src/main/resources/templates/formLogin.html
  src/main/resources/templates/formRegistro.html
  src/main/resources/templates/index.html
  src/main/resources/templates/modals.html
  src/main/resources/templates/perfil.html
  src/main/resources/templates/teclados.html
Labels: enhancement

#29 Feature
  src/main/java/madstodolist/Application.java
  src/main/java/madstodolist/TiendaLolApplication.java
  src/main/java/madstodolist/controller/AdminController.java
  src/main/java/madstodolist/controller/CarritoController.java
  src/main/java/madstodolist/controller/TareaController.java
  src/main/java/madstodolist/dto/ProductoData.java
  src/main/java/madstodolist/dto/TareaData.java
  src/main/java/madstodolist/model/Tarea.java
  src/main/java/madstodolist/model/Usuario.java
  src/main/java/madstodolist/repository/TareaRepository.java
  src/main/java/madstodolist/service/CategoriaService.java
  src/main/java/madstodolist/service/InitDbService.java
  src/main/java/madstodolist/service/ProductoService.java
  src/main/java/madstodolist/service/TareaService.java
  src/main/java/madstodolist/service/TareaServiceException.java
  src/main/resources/templates/admin.html
  src/main/resources/templates/formEditarTarea.html
  src/main/resources/templates/formNuevaTarea.html
  src/main/resources/templates/listaTareas.html
  src/main/resources/templates/modals.html
  src/main/resources/templates/perfil.html
  src/test/java/madstodolist/controller/TareaWebTest.java
  src/test/java/madstodolist/controller/TiendaControllerTest.java
  src/test/java/madstodolist/controller/UsuarioPruebaWebTest.java
  src/test/java/madstodolist/repository/TareaTest.java
  src/test/java/madstodolist/repository/UsuarioTest.java
  src/test/java/madstodolist/service/CategoriaServiceTest.java
  src/test/java/madstodolist/service/ProductoServiceTest.java
  src/test/java/madstodolist/service/TareaServiceTest.java
  src/test/java/madstodolist/service/UsuarioPruebaServiceTest.java
  src/test/resources/clean-db.sql
Labels: enhancement

#34 Feature
  README.md
  pom.xml
  src/main/java/madstodolist/TiendaLolApplication.java
  src/main/java/madstodolist/controller/exception/TareaNotFoundException.java
  src/main/java/madstodolist/controller/exception/UsuarioNoLogeadoException.java
  src/main/java/madstodolist/repository/ProductoRepository.java
  src/main/resources/application.properties
  src/main/resources/database/ScriptBBDD.sql
  src/main/resources/static/img/CapturasTests.png
  src/main/resources/static/img/SQL.png
  src/main/resources/static/img/a
Labels: documentation, enhancement

#35 feat(BBDD): Fix issues with aws
  src/main/java/madstodolist/TiendaLolApplication.java
  src/main/java/madstodolist/controller/CarritoController.java
  src/main/java/madstodolist/model/Categoria.java
  src/main/java/madstodolist/model/DetallePedido.java
  src/main/java/madstodolist/model/Pedido.java
  src/main/java/madstodolist/model/PedidoProducto.java
  src/main/java/madstodolist/model/Producto.java
  src/main/java/madstodolist/service/InitDbService.java
  src/main/java/madstodolist/service/PedidoService.java
  src/main/resources/application.properties
  src/main/resources/database/ScriptBBDD.sql
  src/main/resources/static/img/CamiJinx.jpg
  src/main/resources/static/img/CamiSeta.jpg
  src/main/resources/static/img/FiguraYasuo.jpg
  src/main/resources/static/img/TecladoJinx.jpg
  src/main/resources/static/img/TecladoMancos.jpg
  src/main/resources/static/img/figuraAhri.jpg
  src/main/resources/templates/camisetas.html
  src/main/resources/templates/perfil.html
Labels: enhancement

#36 Docs(Readme.md): add doc
  README.md
  src/main/java/madstodolist/service/PedidoService.java
  src/main/resources/static/img/panelGithub.png
Labels: documentation
